Product
izaLukawska/online_shop_project pull request #1
Opened 2024-08-29 18:59 UTC by izaLukawska

in task you wrote I have to describe every getter but im not sure if I should do it in class or somewhere else?

2024-08-29 19:19 UTC, Wlodek-YouCanDev requested changes

2024-08-29 19:19 UTC, Wlodek-YouCanDev commented on src/main/java/com/youcandev/store/model/Product.java
> +    public static class ProductBuilder{
Zrób ten builder wtedy osobną klasą, będzie bardziej czytelny kod. Poszukaj jak to zrobić na necie, ale dużej różnicy nie będzie

2024-09-02 13:52 UTC, Wlodek-YouCanDev requested changes

2024-09-02 13:52 UTC, Wlodek-YouCanDev commented on src/main/java/com/youcandev/store/model/Product.java
> +    protected Product(ProductBuilder productBuilder){}
Dlaczego tu protected dałeś?

2024-09-02 14:50 UTC, izaLukawska commented on src/main/java/com/youcandev/store/model/Product.java
> +    protected Product(ProductBuilder productBuilder){}
ponieważ w ProductBuilder mam metodę Product build(){return new Product(this)} I inaczej nie miałabym dostępu do obiektu Product

2024-09-02 16:50 UTC, izaLukawska commented
moved the builder to product class, ready for review

2024-09-02 18:53 UTC, Wlodek-YouCanDev approved these changes

2024-09-02 18:58 UTC, merged