wrote test for Customer class and implemented lombok
izaLukawska/online_shop_project pull request #3
Opened 2024-09-05 10:31 UTC by izaLukawska

the class coverage is 100% but method 37%. is this because I didn't write tests for getters and setters? if so should I always do it

2024-09-05 14:42 UTC, Wlodek-YouCanDev requested changes

2024-09-05 14:42 UTC, Wlodek-YouCanDev commented on src/test/java/com/youcandev/store/model/CustomerTest.java
> +class CustomerTest {
To jest zbędny trochy test. Bo tak naprawdę testujesz tutaj add metode klasy ArrayList. Lepiej napisz test pod metode calculateTotalPrice

2024-09-05 16:26 UTC, izaLukawska commented on src/test/java/com/youcandev/store/model/CustomerTest.java
> +class CustomerTest {
czyli usunąć w ogóle ta klasę? napisałam dla calculateTotalPrice jak coś

2024-09-05 16:34 UTC, Wlodek-YouCanDev requested changes

2024-09-05 16:34 UTC, Wlodek-YouCanDev commented on src/test/java/com/youcandev/store/model/CustomerTest.java
> +class CustomerTest {
Tak

2024-09-05 16:34 UTC, Wlodek-YouCanDev commented on src/test/java/com/youcandev/store/model/OrderTest.java
> +        //when
Odstępy przed when i then. Dalej var order = new Order to jest given, czyl ito co masz jako dane testowe. W assertEquals zamiast tego BigDecimal.valueOf(350) ma być expectedResult

2024-09-05 16:47 UTC, izaLukawska commented on src/test/java/com/youcandev/store/model/OrderTest.java
> +        //when
done

2024-09-05 16:50 UTC, Wlodek-YouCanDev requested changes

2024-09-05 16:50 UTC, Wlodek-YouCanDev commented on src/test/java/com/youcandev/store/model/OrderTest.java
>          assertEquals(BigDecimal.valueOf(350), result);
Tak, rób lepiej wolny ale bez blędów. Po pierwsze utworzyłeś zmienną expectedResult ale nie używasz jej. Po drugie prder.setProducts też idzie w given sekcji bo to są dane wejściowe.

2024-09-07 08:45 UTC, izaLukawska commented
Ready for review

2024-09-09 14:05 UTC, Wlodek-YouCanDev requested changes

2024-09-09 14:05 UTC, Wlodek-YouCanDev commented on src/main/java/com/youcandev/store/model/Customer.java
> +
Zbędna pusta linijka kodu pomiedzy adnotacja i nazwa klasy

2024-09-09 14:05 UTC, Wlodek-YouCanDev commented on src/main/java/com/youcandev/store/model/Order.java
> +
Tez zbedna pusta linija kodu

2024-09-09 14:05 UTC, Wlodek-YouCanDev commented on src/main/java/com/youcandev/store/model/Product.java
> +
To samo

2024-09-09 14:05 UTC, Wlodek-YouCanDev commented on src/test/java/com/youcandev/store/model/OrderTest.java
> +        BigDecimal expectedResult = BigDecimal.valueOf(350);
Expected result to tez wartosc ktora juz masz na poczatku testu, wiec given

2024-09-09 15:29 UTC, izaLukawska commented
deleted redundant lines, ready for review

2024-09-09 16:14 UTC, Wlodek-YouCanDev approved these changes

2024-09-09 16:18 UTC, merged